---
- name: "Configure .bashrc"
  ansible.builtin.template:
    src: ".bashrc.j2"
    dest: "{{ postgresql_home_directory }}/.bashrc"
    owner: "{{ postgresql_sys_user }}"
    group: "{{ postgresql_sys_group }}"
    mode: "0700"
