---
- name: "Création de l'utilisateur de base de données {{ user_name }}"
  community.postgresql.postgresql_user:
    name: "{{ user_name }}"
    password: "{{ user_password }}"
    role_attr_flags: "{{ user_roles }}"
    login_user: "postgres"
  no_log: true
  become: true
  become_user: "postgres"
  vars:
    ansible_ssh_pipelining: "true"
