---
- name: "Postgresql: Managing roles"
  community.postgresql.postgresql_user:
    db: "{{ postgresql_system_database }}"
    name: "{{ item.name }}"
    password: "{{ item.password | default(omit) }}"
    role_attr_flags: "{{ item.role_attr_flags }}"
    port: "{{ item.port | default(postgresql_port_number) }}"
    state: "{{ item.state }}"
    login_user: "{{ postgresql_default_owner }}"
    login_password: "{{ vault_postgresql_password | default(omit) }}"
  loop: "{{ postgresql_roles }}"
  # Masqué uniquement pour les rôles avec mot de passe, pour garder les erreurs lisibles.
  no_log: "{{ item.password is defined }}"
  when: postgresql_roles is defined
  become: true
  become_user: "{{ postgresql_default_owner }}"
  vars:
    ansible_ssh_pipelining: "true"
