---
- name: "Gestion des crons"
  ansible.builtin.cron:
    user: "{{ cron_schedule.user }}"
    name: "{{ cron_schedule.name }}"
    cron_file: "{{ cron_schedule.cron_file }}"
    job: "{{ cron_schedule.job }}"
    state: "{{ cron_schedule.state }}"
    disabled: "{{ cron_schedule.disabled }}"
    minute: "{{ cron_schedule.minute }}"
    hour: "{{ cron_schedule.hour }}"
    day: "{{ cron_schedule.day }}"
    month: "{{ cron_schedule.month }}"
    weekday: "{{ cron_schedule.weekday }}"
  loop: "{{ cron_schedules }}"
  loop_control:
    loop_var: cron_schedule

- name: "Gestion des droits des fichiers crons"
  ansible.builtin.file:
    path: "/etc/cron.d/{{ cron_schedule.cron_file }}"
    owner: "{{ cron_schedule.user }}"
    group: "{{ cron_file_group }}"
    mode: "0644"
  loop: "{{ cron_schedules }}"
  loop_control:
    loop_var: cron_schedule
