---
- name: "Inclusion des prérequis logrotate"
  ansible.builtin.import_tasks: prerequisites.yml

- name: "Inclusion de la gestion des fichiers logrotate"
  ansible.builtin.import_tasks: logrotate_files_manager.yml
  when: logrotate_files is defined
