---
- name: "Chargement des variables spécifiques à la distribution"
  ansible.builtin.include_vars: '{{ ansible_facts["os_family"] }}.yml'
  when: ansible_facts['os_family'] == 'RedHat'

- name: "Gestion de l'authentification host based"
  ansible.builtin.import_tasks: hba_manager.yml
  when: pgbouncer_hba_entries is defined

- name: "Gestion de pgbouncer.ini et des bases de données"
  ansible.builtin.import_tasks: database_entries_manager.yml

- name: "Gestion de la userlist"
  ansible.builtin.import_tasks: userlist_manager.yml
  when: pgbouncer_userlist is defined
