---
- name: Configure user list file (if entries are configured).
  ansible.builtin.template:
    src: "userlist.txt.j2"
    dest: "{{ pgbouncer_auth_file }}"
    owner: "{{ pgbouncer_sys_user }}"
    group: "{{ pgbouncer_sys_group }}"
    mode: "0600"
  no_log: true
  when: pgbouncer_userlist is defined
  notify: Reload pgbouncer
