---
- name: "récupération du contenu du fichier {{ parameter_src_file }}"
  ansible.builtin.slurp:
    src: "{{ parameter_src_file }}"
  register: src_file

- name: "Copie de fichier : {{ parameter_src_file ~ ' vers ' ~ parameter_dest_file }}"
  ansible.builtin.copy:
    content: "{{ src_file.content | b64decode }}"
    dest: "{{ parameter_dest_file }}"
    force: "{{ parameter_force }}"
    group: "{{ parameter_group }}"
    owner: "{{ parameter_owner }}"
    mode: "{{ parameter_mode }}"
