---
- name: "Remplacement par expression régulière dans {{ file_path ~ ' : ' ~ parameter_regexp ~ ' -> ' ~ parameter_value }}"
  ansible.builtin.lineinfile:
    path: "{{ file_path }}"
    regexp: "{{ parameter_regexp }}"
    line: "{{ parameter_value }}"
    state: present
