---
- name: "Déploiement de git"
  hosts: "{{ target_hosts | default([]) }}"
  become: true
  tasks:
    - name: "Exécution du déploiement de git"
      ansible.builtin.include_role:
        name: git
        tasks_from: "config_manager.yml"
