---
- name: "Gestion de mysecureshell"
  hosts: "{{ target_hosts | default([]) }}"
  become: true
  tasks:
    - name: "Gestion de mysecureshell"
      ansible.builtin.include_role:
        name: mysecureshell
